name: lfs-ci

on:
  pull_request:
    paths:
      - '**.bin'
      - '**.glb'
      - '**.gltf'
      - '**.ipynb'
      - '**.mp3'
      - '**.mp4'
      - '**.np'
      - '**.ogg'
      - '**.png'
      - '**.tensor'
      - '**.vox'
      - '**.wasm'
      - '**.webm'
      - 'scratch/alpha_terrain.json'
      - '.gitattributes'
      - '.github/actions/cached-lfs-pull/**'
      - '.github/workflows/lfs-ci.yml'

jobs:
  lfs-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: git lfs pull
        uses: ./.github/actions/cached-lfs-pull
      - name: Check for git lfs files that should be "pointers" but are not.
        run: git lfs fsck
